@startuml

left to right direction
skinparam packageStyle rectangle
skinparam usecaseFontSize 12
skinparam actorStyle awesome

actor "Legacy CA/TA\n앱 개발자" as CLAD
actor "보안 시나리오\n앱 개발자" as CSAD
actor "검증팀" as CVT

rectangle "Linux pKVM 기반 가상화 보안 플랫폼" {

  package "Host OS" {
    usecase "UC-01\nGP API를 통한 Host-TEE간 통신" as UC01
    usecase "UC-02\npVM 생성/실행/중단/삭제" as UC02
    usecase "UC-03\npVM 상태 변경 확인" as UC03
    usecase "UC-04\npVM으로 RPC 통신" as UC04
    usecase "UC-05\nPayload, Memory, CPU 정보 설정" as UC05
    usecase "UC-06\npVM으로 보안 File System 마운트" as UC06
  }

  package "pVM" {
    usecase "UC-08\nHost으로 RPC 통신" as UC08
    usecase "UC-09\nGP API를 통한 pVM-TEE간 통신" as UC09
  }

  package "검증" {
    usecase "UC-10\n메모리 격리 검증" as UC10
    usecase "UC-11\npVM 장애 격리 검증" as UC11
    usecase "UC-12\n성능 벤치마크 측정" as UC12
  }
}

CLAD --> UC01

CSAD --> UC02
CSAD --> UC03
CSAD --> UC04
CSAD --> UC05
CSAD --> UC06
CSAD --> UC08
CSAD --> UC09

CVT --> UC10
CVT --> UC11
CVT --> UC12

@enduml
